# Транспонирование

Транспонирование - процедура преобразования матрицы которую следует отличать от поворота, с которым ее иногда путают. Транспонирование заменяет строки на столбцы и наоборот. Если изначально матрица выглядит так:

$$
\mathbf{A} = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix},
$$

то после транспонирования:

$$
\mathbf{A}^T = 
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}.
$$

Вроде всё просто, но нужно разобраться со следующим:  
как будет выглядеть транспонированное произведение матриц?

$$
(\mathbf{AB})^T = ?
$$

Во-первых, разберёмся с тем, чему будет равна транспонированная сумма. В индексной записи сумма матриц:

$$
\mathbf{C} = \mathbf{A} + \mathbf{B},
$$

$$
c_{ij} = a_{ij} + b_{ij},
$$

тогда элемент транспонированной матрицы:

$$
c^{T}_{ij} = c_{ji} = a_{ji} + b_{ji} = a^{T}_{ij} + b^{T}_{ij}.
$$

Получается, транспонированная сумма равна сумме транспонированных матриц:

$$
(\mathbf{A} + \mathbf{B})^T = \mathbf{A}^T + \mathbf{B}^T.
$$

Чтобы выяснить, как будет выглядеть транспонированное произведение, для начала попробуем заменить матрицу $\mathbf{B}$ вектором $\mathbf{b}$:

$$
(\mathbf{Ab})^T = 
(b_1 \mathbf{a_1} + b_2 \mathbf{a_2} + b_3  \mathbf{a_3})^T =
b_1 \mathbf{a_1}^T + b_2 \mathbf{a_2}^T + b_3  \mathbf{a_3}^T.
$$

То есть получается, что в результате будет не вектор-столбец, а вектор-строка с теми же координатами, который получен линейной комбинацией строк $\mathbf{A}^T$, которые для $\mathbf{A}$ были столбцами. Если подсмотреть в различные представления произведения матриц, то это можно интерпретировать так: колонка вектора $\mathbf{b}^T$ (одно число) умножается на строку матрицы $\mathbf{A}^T$. Из одного из представлений произведения (способ 4) следует, что:

$$
(\mathbf{Ab})^T 
= \mathbf{b}^T \mathbf{A}^T.
$$

Теперь легко показать следующее:

$$
(\mathbf{AB})^T =
\begin{bmatrix}
\mathbf{A} \mathbf{b_1} & \mathbf{A} \mathbf{b_2} & \dots
\end{bmatrix}^T =
\begin{bmatrix}
\mathbf{b_1}^T \mathbf{A}^T \\
\mathbf{b_2}^T \mathbf{A}^T \\ 
\vdots
\end{bmatrix} =
\mathbf{B}^T \mathbf{A}^T.
$$

Транспонирование меняет порядок!

Так-же очевидно, что 
$$
(\mathbf{A}^T)^T
= \mathbf{A}.
$$

In [1]:
# Транспонирование в numpy для матрицы A задается как A.T
import numpy as np

A = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
print(A)
print(A.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [16]:
# Проверим правило транспонирования произведения:

B = np.array(
    [
        [2, 1, 5],
        [4, 3, 4]
    ]
)

print("(BA)^T = ")
print(np.dot(B, A).T)
print("A^T B^T = ")
print(np.dot(A.T, B.T))


(BA)^T = 
[[30 33]
 [38 44]]
A^T B^T = 
[[30 33]
 [38 44]]


**Симметричная матрица** — это матрица, для которой выполняется равенство: 

$$\mathbf{S} = \mathbf{S}^T.$$

Симметричную матрицу можно сконструировать, умножив исходную матрицу на её транспонированную:

$$
\mathbf{C} = \mathbf{A} \mathbf{A}^T.
$$

Проверим симметричность:

$$
(\mathbf{A} \mathbf{A}^T)^T = \mathbf{A}^T (\mathbf{A}^T)^T = \mathbf{A} \mathbf{A}^T = \mathbf{C}^T.
$$

Таким образом, $\mathbf{C}$ действительно симметрична.

Симметричной её называют, потому что она как бы зеркально отражена относительно своей главной диагонали.

In [20]:
#Сконструируем тройку симметричных матриц из уже использованных A и B
print(A @ A.T)
print(A.T @ A)
print(B @ B.T)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
[[35 44]
 [44 56]]
[[30 31]
 [31 41]]


Ну и вишенка на торте:
Теперь можно пользоваться **матричной нотацией** вместо скалярного '$\cdot$' и записывать скалярное произведение так:

$$
\mathbf{x} \cdot \mathbf{y} = \mathbf{x}^T \mathbf{y}
$$

Так-же можно ввести другое произведение:

$$
\mathbf{x} \cdot \mathbf{y} = \mathbf{x}^T \mathbf{y}
$$

Так же можно ввести **внешнее произведение**:

$$
\mathbf{x} \cdot \mathbf{y}^T = \mathbf{Q},
$$

результатом которого является матрица.


Вот как можно работаь с этим в numpy:

In [12]:
# Векторы для примера
x = np.array([1, 2, 3])  # Вектор-строка
y = np.array([3, 4, 5])  # Вектор-строка

# Изменение формы вектора x для создания вектор-столбца
x.resize((3, 1))  # Теперь x — вектор-столбец

# Внутреннее произведение (dot product)
# Внутреннее произведение — это сумма попарных произведений элементов двух векторов
dot_product = np.dot(x.T, y)  # Результат — число (скаляр)

# Внешнее произведение (outer product)
# Внешнее произведение создает матрицу, где каждый элемент — это произведение элементов из x и y
outer_product = np.outer(x, y)  # Результат — матрица

# Вывод результатов
print("Вектор-столбец x:")
print(x)

print("\nТранспонированный вектор x^T (вектор-строка):")
print(x.T)

print("\nВектор-строка y:")
print(y)

print("\nВнутреннее произведение x, y:")
print(dot_product)

print("\nВнешнее произведение x, y:")
print(outer_product)

Вектор-столбец x:
[[1]
 [2]
 [3]]

Транспонированный вектор x^T (вектор-строка):
[[1 2 3]]

Вектор-строка y:
[3 4 5]

Внутреннее произведение x, y:
[26]

Внешнее произведение x, y:
[[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
