# Факторизация

## LU-факторизация

LU-факторизация — это разложение квадратной матрицы $\mathbf{A}$ на две матрицы: нижнетреугольную матрицу $\mathbf{L}$ (Lower) и верхнетреугольную матрицу $\mathbf{U}$ (Upper), так что:

$$
\mathbf{A} = \mathbf{L} \mathbf{U}.
$$

- **Нижнетреугольная матрица $\mathbf{L}$** содержит элементы на диагонали и ниже неё, а выше диагонали все элементы равны нулю.
- **Верхнетреугольная матрица $\mathbf{U}$** содержит элементы на диагонали и выше неё, а ниже диагонали все элементы равны нулю.

Эта факторизация особенно полезна для решения систем линейных уравнений $\mathbf{A} \mathbf{x} = \mathbf{b}$, так как она позволяет разложить задачу на два этапа:
1. Решение системы $\mathbf{L} \mathbf{y} = \mathbf{b}$ методом прямой подстановки.
2. Решение системы $\mathbf{U} \mathbf{x} = \mathbf{y}$ методом обратной подстановки.

LU-факторизация применяется в численных методах для ускорения вычислений, например, при решении систем линейных уравнений  и нахождении обратной матрицы.


## Матрицы элементарных преобразований

Чтобы понять, как можно сконструировать разложение, давайте посмотрим, как мы в процессе элиминации получаем верхнетреугольную матрицу. Последовательно применяя определённый набор элементарных преобразований, мы исключаем из исходной матрицы все элементы ниже главной диагонали. Однако эти преобразования остаются скорее процедурными, чем математическими. Возможно, существует способ выразить их на математическом, символическом языке?

И вот тут начинается самое интересное. Стрэнг показывает, что все элементарные операции, используемые в процессе элиминации, можно представить как действия с матрицами. Умножая матрицу на специально сконструированные элементарные матрицы, мы можем реализовать такие операции, как перестановка строк, вычитание строк и другие.

1. Самое простое преобразование — **идентичное**. Оно ничего не изменяет. На выходе такого преобразования получается то же самое, что и на входе. Его матрица уже попадалась в определении обратной матрицы.

Это преобразование задаётся квадратной матрицей, у которой на главной диагонали стоят единицы, а все остальные элементы равны нулю. Например, для матрицы $\mathbf{A}_{3 \times 3}$ матрица идентичного преобразования будет выглядеть так:

$$
\mathbf{I} =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}.
$$

В результате применения этого преобразования:

$$
\mathbf{I A} = \mathbf{A}.
$$

2. **Замена строк** легко конструируется из идентичного преобразования. Из способов матричного умножения понятно, что в матрице преобразования строка с одной единицей и остальными нулями, при умножении даст тот номер строки исходной матрицы на котором стояла единица.

In [1]:
import numpy as np

A = np.array(
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]
)
Q = np.zeros_like(A).astype("float64")
Q[0][2] = 1
print(Q)
Q @ A


[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[7., 8., 9.],
       [0., 0., 0.],
       [0., 0., 0.]])

Таким образм поменяв строки в матрице идентичного преобразования можно получить матрицу пермутации (перестановки).

$$
\mathbf{I} =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix},
$$

Поменяем первую и вторую строку и получим:

$$
\mathbf{P}_{1 \thinspace 2} =
\begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix},
$$

Посмотрим как это работает:

In [2]:
A = np.array(
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]
)
P_12 = np.zeros_like(A).astype("float64")
P_12[0][1] = 1
P_12[1][0] = 1
P_12[2][2] = 1
print(P_12)
P_12 @ A

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


array([[4., 5., 6.],
       [1., 2., 3.],
       [7., 8., 9.]])

Ну и вишенка на торте: если в строке оказывается не одна единица, а единица и ещё одно число, то, по идее, у нас должны появиться две строки в одном месте. Давайте протестируем эту догадку:

In [3]:
A = np.array(
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]
)
E = np.identity(3)
E[1][0] = -1
print(E)
E @ A

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]


array([[1., 2., 3.],
       [3., 3., 3.],
       [7., 8., 9.]])

Видно, что матрица  

$$
\mathbf{E} =
\begin{bmatrix}
1 & 0 & 0 \\
-1 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix},
$$ 

при умножении на исходную матрицу приводит к тому, что первая строка матрицы $\mathbf{A}$ вычитается из второй строки.  

Таким образом, можно сконструировать элиминирующую матрицу $\mathbf{E}_{ij}$, которая будет похожа на единичную матрицу, но с ненулевым элементом в $i$-ой строке и $j$-ом столбце. Если этот элемент равен $-l$, то при умножении на такую матрицу $j$-я строка умножается на $-l$ и прибавляется к $i$-ой строке.

Таким образом, все преобразования можно выполнить с помощью умножения на специально сконструированные матрицы.

Тогда прямой ход преобразований будет выглядеть как-то так:

$$
\mathbf{P} \cdots \mathbf{E} \cdots \mathbf{P} \cdots \mathbf{E} \mathbf{A} = \mathbf{U}.
$$
В результате этих преобразований получиться $\mathbf{U}$ - верхнетреугольная матрица.

Или можно выделить матрицу  $\mathbf{A}$, можно записать так:

$$
\mathbf{A} = \mathbf{E} ^{-1} \cdots \mathbf{P}^{-1} \cdots \mathbf{E} ^{-1} \cdots \mathbf{P}^{-1} \mathbf{U}.
$$

Где $\mathbf{E}$ и $\mathbf{P}$  различные матрицы преобразований.

Все преобразования с заменой строк при помощи матриц $\mathbf{P}$ можно выполнить как в начале преобразования, так и в конце. При этом все матрицы $\mathbf{P}$, будучи перемноженными, "спрессуются" в одну матрицу. Матрицы $\mathbf{E}$, обладая нижнетреугольным видом, также при перемножении образуют одну нижнетреугольную матрицу.

1. Тогда матрицу $\mathbf{A}$ можно разложить следующим образом на множители: нижнетреугольную и верхнетреугольную матрицы $\mathbf{L}$ и $\mathbf{U}$:

   $$
   \mathbf{P} \mathbf{A} = \mathbf{L} \mathbf{U},
   $$

2. Альтернативная запись разложения:

   $$
   \mathbf{A} = \mathbf{L}_1 \mathbf{P}_1 \mathbf{U}_1,
   $$

   где:
   - $\mathbf{L}_1$ — модифицированная нижнетреугольная матрица.
   - $\mathbf{P}_1$ — перестановочная матрица, относящаяся к строкам матрицы $A$.
   - $\mathbf{U}_1$ — модифицированная верхнетреугольная матрица.