# Правила обращения с матрицами

Работа с матрицами — это расширение работы с векторами, поскольку матрицы можно рассматривать как набор "упакованных" векторов. Операции с матрицами основываются на тех же принципах, что и для векторов, но включают дополнительные правила. Ниже описаны основные операции с матрицами.

## Сложение
Со сложением всё просто:  
Мы складываем соответствующие элементы, как и в векторах.

## Умножение на число
Здесь всё также аналогично векторному случаю:  
Каждый элемент матрицы умножается на число.

## Умножение

1. Поскольку матрицу можно представить как набор вектор-столбцов, умножение матриц можно рассматривать следующим образом:

   $$
   \mathbf{A B} = \mathbf{A} \cdot \left[ \begin{array}{} \mathbf{b_1} & \mathbf{b_2} & \mathbf{b_3} \end{array} \right] = \left[\begin{array}{} \mathbf{A} \cdot \mathbf{b_1} & \mathbf{A} \cdot \mathbf{b_2} & \mathbf{A} \cdot \mathbf{b_3} \end{array}  \right]
   $$

   Матрица $\mathbf{A}$ действует на каждый вектор-столбец матрицы $\mathbf{B}$.

Если развить этот подход и представить матрицу $\mathbf{A} $ как совокупность вектор-строк, то получится следующее:
   
   $$
   \mathbf{A} \cdot \mathbf{b_1} = 
   \begin{bmatrix}
   a_1 \\
   a_2 \\
   a_3 
   \end{bmatrix} 
   \begin{bmatrix}
   b_1 &  b_2 &  b_3 
   \end{bmatrix} 
   $$

2.   Отсюда следует, что чтобы получить элемент результирующей матрицы $\mathbf{C}$, нужно соответствующую строку $\mathbf{A}$ умножить на соответствующий столбец $\mathbf{B}$:

   $$
   c_{ij} = \text{i-ая строка} \thinspace \mathbf{A} \cdot \text{j-ый столбец} \thinspace \mathbf{B}.
   $$

   Из этого правила следует, что матрицы должны быть согласованы по размеру. У матрицы $\mathbf{A}$ количество элементов в строке (количество столбцов) должно быть равно количеству элементов в столбце матрицы $\mathbf{B}$ (количество строк). Это правило можно записать так:

   $$
   \mathbf{A}_{m \times n} \mathbf{B}_{n \times q} = \mathbf{C}_{m \times q},
   $$

   где первый индекс — это количество строк, а второй — количество столбцов.

Зная два три способа, можно получить ещё пару представлений:

3. $i$-ая строка $\mathbf{A}$ умножается матрично на $\mathbf{B}$, и получается $i$-ая строка матрицы $\mathbf{AB}$.

4. Если поступить наоборот и представить матрицу $\mathbf{A}$ как совокупность вектор-столбцов, а матрицу $\mathbf{B}$ как совокупность вектор-строк, то, умножив соответствующие столбцы на строки, получим:
   
   $$
   \begin{bmatrix}
   \text{колонка}_1 &  \text{колонка}_2 &  \text{колонка}_3 
   \end{bmatrix} 

   \begin{bmatrix}
   \text{строка}_1 \\
   \text{строка}_2 \\
   \text{строка}_3 
   \end{bmatrix} =
   \text{колонка}_1 \cdot \text{строка}_1 + 
   \text{колонка}_2 \cdot \text{строка}_2 + 
   \text{колонка}_3 \cdot \text{строка}_3,
   $$
   
   где каждое слагаемое будет матрицей.

В python numpy из коробки умеет умножать матрицы при помощи знакомого оператора '@' или np.dot(). Код ниже продемонстритует, что первый способ умножения дает тот, же результат, что и третий (который чаще всего дается при изучении линейной алгебры).

In [1]:
import numpy as np

def split_array(array: np.ndarray, format: str = "rows") -> list:
    """
    Splits a NumPy ndarray into a list of vector-columns or vector-rows.

    Parameters
    ----------
    array : ndarray
        A 2D NumPy array to be split.
    format : str, optional
        Specifies the format of the returned vectors. 
        - "rows": returns a list of vector-rows (default).
        - "columns": returns a list of vector-columns.

    Returns
    -------
    list
        A list of 1D NumPy arrays (vector-rows or vector-columns).

    Raises
    ------
    ValueError
        If `format` is not "rows" or "columns".

    Examples
    --------
    >>> import numpy as np
    >>> array = np.array([[1, 2, 3], [4, 5, 6]])
    >>> split_array(array, format="rows")
    [array([1, 2, 3]), array([4, 5, 6])]
    
    >>> split_array(array, format="columns")
    [array([1, 4]), array([2, 5]), array([3, 6])]
    """
    if format not in {"rows", "columns"}:
        raise ValueError('Invalid format. Use "rows" or "columns".')
    
    if format == "rows":
        return [array[i, :] for i in range(array.shape[0])]
    elif format == "columns":
        return [array[:, j] for j in range(array.shape[1])]

In [2]:
def mat_mul_as_linear_combination(A: np.ndarray, B: np.ndarray, log: bool = True) -> np.ndarray:
    """
    Perform matrix multiplication and interpret it as a linear combination of column vectors.

    Parameters
    ----------
    A : ndarray
        A 2D NumPy array (matrix) of shape (m, n).
    B : ndarray
        A 2D NumPy array (matrix) of shape (n, p).
    log : bool, optional
        If True, prints the detailed step-by-step process of interpreting the multiplication 
        as a linear combination of column vectors from `A` with the weights provided by 
        the columns of `B`. Default is True.

    Returns
    -------
    ndarray
        The result of matrix multiplication, a 2D NumPy array of shape (m, p).

    Notes
    -----
    This function not only performs the standard matrix multiplication $ C = A \times B $, 
    but also provides an interpretation of the multiplication:
    - The result can be thought of as forming each column of the resulting matrix $ C $
      by taking a linear combination of the columns of `A`, where the coefficients of the 
      combination are the entries of the corresponding column in `B`.
    - The function prints intermediate steps of this process if `log=True`.

    The output includes:
    - The initial multiplication process: `A * B` and the breakdown of `B` into its column vectors.
    - The interpretation of each column of `B` as weights for a linear combination of columns of `A`.
    - The resulting scaled columns before summation.

    Examples
    --------
    >>> import numpy as np
    >>> from some_module import mat_mul_as_linear_combination
    >>> A = np.array([[1, 2], [3, 4]])
    >>> B = np.array([[5, 6], [7, 8]])
    >>> result = mat_mul_as_linear_combination(A, B, log=True)
    [[1 2]
     [3 4]] * [[5 6]
               [7 8]] =
    [[5 7]] ;
    [[6 8]] ;
    =
    5 * [[1]
         [3]] + 7 * [[2]
                    [4]] +
    6 * [[1]
         [3]] + 8 * [[2]
                    [4]] ;
    =
    [[19 22]
     [43 50]]

    See Also
    --------
    numpy.dot : Computes dot product of two arrays.
    numpy.matmul : Matrix multiplication using the `@` operator.
    """
    B_columns = split_array(B, format="columns")
    if log:
        print(A, "*", B, "=", sep="\n")
        for v in B_columns:
            print(f'{A} * {v.T}.T ;')
        print()
    A_columns = split_array(A, format="columns")
    print("=")
    if log:
        for b_col in B_columns:
            for i, val in enumerate(b_col):
                print(f'{val} * {A_columns[i].T}.T  +', end=" ") if i != val.size+1 else print(f'{val} * {A_columns[i].T}.T  ;')
    print("=")
    cols = []
    if log:
        for b_col in B_columns:
            for i, val in enumerate(b_col):
                cols.append(val * A_columns[i].T)
                print(f'{val * A_columns[i].T}.T  +', end=" ") if i != val.size+1 else print(f'{val * A_columns[i].T}.T  ;')
    
    return np.array([np.sum(cols[:3], 0), np.sum(cols[3:6], 0), np.sum(cols[6:], 0)]).T

In [3]:
A = np.array(
    [
        [4, 3, 2],
        [1, 3, 1],
        [3, 4, 7]
    ]
        )
B = np.array(
    [
        [2, 3, 5],
        [3, 2, 1],
        [6, 5, 2]
    ]
        )
print(mat_mul_as_linear_combination(A, B))

[[4 3 2]
 [1 3 1]
 [3 4 7]]
*
[[2 3 5]
 [3 2 1]
 [6 5 2]]
=
[[4 3 2]
 [1 3 1]
 [3 4 7]] * [2 3 6].T ;
[[4 3 2]
 [1 3 1]
 [3 4 7]] * [3 2 5].T ;
[[4 3 2]
 [1 3 1]
 [3 4 7]] * [5 1 2].T ;

=
2 * [4 1 3].T  + 3 * [3 3 4].T  + 6 * [2 1 7].T  ;
3 * [4 1 3].T  + 2 * [3 3 4].T  + 5 * [2 1 7].T  ;
5 * [4 1 3].T  + 1 * [3 3 4].T  + 2 * [2 1 7].T  ;
=
[8 2 6].T  + [ 9  9 12].T  + [12  6 42].T  ;
[12  3  9].T  + [6 6 8].T  + [10  5 35].T  ;
[20  5 15].T  + [3 3 4].T  + [ 4  2 14].T  ;
[[29 28 27]
 [17 14 10]
 [60 52 33]]


In [4]:
print(A @ B)

[[29 28 27]
 [17 14 10]
 [60 52 33]]


## Матричные операции подчиняются следующим законам:

   

- $A + B = B + A$ — (коммутативный закон для сложения).
- $c(A + B) = cA + cB$ — (распределительный закон).
- $A + (B + C) = (A + B) + C$ — (ассоциативный закон для сложения).

Три дополнительных закона справедливы для умножения, но $AB \neq BA$ — не один из них:  
(«коммутативный закон» для умножения обычно нарушается)

- $A(B + C) = AB + AC$ — (распределительный закон слева).  
- $(A + B)C = AC + BC$ — (распределительный закон справа).  
- $A(BC) = (AB)C$ — (ассоциативный закон для произведения $ABC$; скобки не обязательны).

Простой пример того, что $AB \neq BA$:

In [5]:
print('A =\n', A)
print('B =\n', B)
print('AB =\n', A @ B)
print('BA =\n', B @ A)

A =
 [[4 3 2]
 [1 3 1]
 [3 4 7]]
B =
 [[2 3 5]
 [3 2 1]
 [6 5 2]]
AB =
 [[29 28 27]
 [17 14 10]
 [60 52 33]]
BA =
 [[26 35 42]
 [17 19 15]
 [35 41 31]]
