# Обратная матрица

Матрица $\mathbf{A}$ называется **обратимой**, если существует такая матрица $\mathbf{A}^{-1}$, что

$$\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I}.$$

Здесь $\mathbf{I}$ — это **единичная матрица**, которая имеет такие свойства:
- Она является квадратной (количество строк равно количеству столбцов).
- Все элементы на главной диагонали равны $1$, а остальные элементы равны $0$. Например, для матриц размером $2 \times 2$ и $3 \times 3$ это выглядит так:
  $$
  \mathbf{I}_{2 \times 2} = \begin{bmatrix} 
  1 & 0 \\ 
  0 & 1 
  \end{bmatrix}, \quad
  \mathbf{I}_{3 \times 3} = \begin{bmatrix} 
  1 & 0 & 0 \\ 
  0 & 1 & 0 \\ 
  0 & 0 & 1 
  \end{bmatrix}.
  $$
- Умножение любой матрицы $\mathbf{A}$ на единичную матрицу $\mathbf{I}$ не изменяет её:  
  $$
  \mathbf{A} \cdot \mathbf{I} = \mathbf{I} \cdot \mathbf{A} = \mathbf{A}.
  $$

По поводу обратимости можно сделать следующие замечания:
1. Если матрица обратима, то в процессе приведения её к диагональному виду все опорные элементы будут находиться на диагонали.
2. Обратная матрица единственна.
3. Уравнение $\mathbf{A}\mathbf{x} = \mathbf{b}$ имеет единственное решение:  
   
   $$
   \mathbf{A}\mathbf{x} = \mathbf{b} \Longleftrightarrow \mathbf{A}^{-1}\mathbf{A}\mathbf{x} = \mathbf{A}^{-1}\mathbf{b} \Longleftrightarrow \mathbf{I}\mathbf{x} = \mathbf{A}^{-1}\mathbf{b} \Longleftrightarrow \mathbf{x} = \mathbf{A}^{-1}\mathbf{b}.
   $$

4. Если существует ненулевой вектор $\mathbf{x}$, такой что $\mathbf{A}\mathbf{x} = \mathbf{0}$, то матрица $\mathbf{A}$ необратима.

## Обратная матрица произведения матриц
Пускай некая матрица получается произведением:
$\mathbf{A} \mathbf{B}$
Тогда вот такое выражение должно быть верно:

$$(\mathbf{A} \mathbf{B})^{-1} (\mathbf{A} \mathbf{B}) = \mathbf{I}$$

Если умножить справа на $\mathbf{B}^{-1} \mathbf{A}^{-1}$ обе части:

$$(\mathbf{A} \mathbf{B})^{-1} (\mathbf{A} \mathbf{B}) \mathbf{B}^{-1} \mathbf{A}^{-1} = \mathbf{I} \mathbf{B}^{-1} \mathbf{A}^{-1}$$

И учесть что умножение матриц ассциативно (закон про скобки), сокращая попарно множители:

$$(\mathbf{A} \mathbf{B})^{-1} \mathbf{I}  = \mathbf{B}^{-1} \mathbf{A}^{-1}$$

$$(\mathbf{A} \mathbf{B})^{-1}   = \mathbf{B}^{-1} \mathbf{A}^{-1}$$

Получается, что обратная матрица произведения при раскрытии скобок меняет порядок умножения, прямо как транспонирование!

А как на счет одновременного транспонирования и обращения матрицы?
Если у матрицы есть обратная, тогда:

$$\mathbf{A}^{-1} \mathbf{A} = \mathbf{I}.$$

Транспонируем обе части:

$$(\mathbf{A}^{-1} \mathbf{A})^T = \mathbf{I}^T,$$

но транспонирование единичной матрицы она и есть, следоваетльно:

$$\mathbf{A}^T (\mathbf{A}^{-1})^T = \mathbf{I}.$$

Теперь это все можно умножить на $(\mathbf{A}^T)^{-1}$ слева, после сокращения сомножителей получиться, что:

$$(\mathbf{A}^{-1})^T = (\mathbf{A}^T)^{-1}.$$




**Нахождение обратной матрицы элиминацией**:

Если у матрицы есть обратная:

$$\mathbf{A} \mathbf{A}^{-1} = \mathbf{I},$$

единичную матрицу можно представить как совокупность вектор-столбцов вида $e_i$, где на $i$-ой строке будет единица, а остальные элементы равны нулю. Обратную матрицу можно представить в виде неизвестных вектор-столбцов.

$$\mathbf{A}
\begin{bmatrix} 
\mathbf{x}_1 & \mathbf{x}_2 & \mathbf{x}_3
\end{bmatrix}
= 
\begin{bmatrix} 
\mathbf{e}_1 & \mathbf{e}_2 & \mathbf{e}_3
\end{bmatrix}.
$$

Всё это можно записать как три системы уравнений вида:

$$\mathbf{A}
\mathbf{x}_i 
= 
\mathbf{e}_i,
$$

но решать их можно сразу все. Для этого из исходной матрицы создаём расширенную, как и в случае обычной элиминации, но вместо вектора свободных коэффициентов приписываем матрицу из вектор-столбцов $\mathbf{e}_i$, т.е. единичную матрицу:

$$
\begin{bmatrix} 
\mathbf{A}&|&\mathbf{I}
\end{bmatrix}.
$$

Приведя матрицу $\mathbf{A}$ преобразованиями к $\mathbf{I}$, в левой части получим обратную матрицу:

$$
\begin{bmatrix} 
\mathbf{A}^{-1} \mathbf{A}&|&\mathbf{A}^{-1}  \mathbf{I}
\end{bmatrix} = 
\begin{bmatrix} 
\mathbf{I}&|&\mathbf{A}^{-1}
\end{bmatrix}.
$$

Попробуем найти обратную матрицу при помощи преобразований:

In [1]:
import numpy as np

def row_swap(A: np.ndarray, k: int, l: int) -> np.ndarray:
    """
    Swap two rows in a NumPy array.

    Parameters
    ----------
    A : ndarray
        A NumPy array of shape (m, n), where `m` is the number of rows 
        and `n` is the number of columns.
    k : int
        The index of the first row to be swapped (0-based indexing).
    l : int
        The index of the second row to be swapped (0-based indexing).

    Returns
    -------
    B : ndarray
        A new NumPy array with rows `k` and `l` swapped. The input array `A` 
        remains unchanged.

    Notes
    -----
    The operation is performed by creating a copy of the input array to 
    ensure the original array is not modified.

    Examples
    --------
    >>> import numpy as np
    >>> A = np.array([[1, 2], [3, 4]])
    >>> row_swap(A, 0, 1)
    array([[3., 4.],
           [1., 2.]])
    """
    m = A.shape[0]  # m is the number of rows in A
    n = A.shape[1]  # n is the number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B


def row_scale(A: np.ndarray, k: int, scale: float) -> np.ndarray:
    """
    Scale a row of a NumPy array by a given factor.

    Parameters
    ----------
    A : ndarray
        A NumPy array of shape (m, n), where `m` is the number of rows 
        and `n` is the number of columns.
    k : int
        The index of the row to be scaled (0-based indexing).
    scale : float
        The factor by which to scale the entries of row `k`.

    Returns
    -------
    B : ndarray
        A new NumPy array with row `k` scaled by `scale`. The input array `A` 
        remains unchanged.

    Notes
    -----
    The operation is performed by creating a copy of the input array to 
    ensure the original array is not modified.

    Examples
    --------
    >>> import numpy as np
    >>> A = np.array([[1, 2], [3, 4]])
    >>> row_scale(A, 1, 2)
    array([[ 1.,  2.],
           [ 6.,  8.]])
    """
    m = A.shape[0]  # m is the number of rows in A
    n = A.shape[1]  # n is the number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B


def row_add(A: np.ndarray, k: int, l: int, scale: float) -> np.ndarray:
    """
    Add a scaled version of one row to another in a NumPy array.

    Parameters
    ----------
    A : ndarray
        A NumPy array of shape (m, n), where `m` is the number of rows 
        and `n` is the number of columns.
    k : int
        The index of the row to be scaled and added (0-based indexing).
    l : int
        The index of the row to be modified (0-based indexing).
    scale : float
        The factor by which to scale the entries of row `k` before adding 
        them to row `l`.

    Returns
    -------
    B : ndarray
        A new NumPy array with row `l` modified. The values of row `l` 
        will be updated by adding the values of row `k`, scaled by `scale`. 
        The input array `A` remains unchanged.

    Notes
    -----
    The operation is performed by creating a copy of the input array to 
    ensure the original array is not modified.

    Examples
    --------
    >>> import numpy as np
    >>> A = np.array([[1, 2], [3, 4]])
    >>> row_add(A, 0, 1, 2)
    array([[ 1.,  2.],
           [ 5.,  8.]])
    """
    m = A.shape[0]  # m is the number of rows in A
    n = A.shape[1]  # n is the number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j] * scale
        
    return B

In [2]:
A = np.array([
    [2, -2, 0],
    [1, 4, 1],
    [2, 4, 8]
])
#Расширенная матрица, образованная 'пристыковкой' единичной матрицы справа.
Aug = np.hstack((A, np.identity(3)))
Aug

array([[ 2., -2.,  0.,  1.,  0.,  0.],
       [ 1.,  4.,  1.,  0.,  1.,  0.],
       [ 2.,  4.,  8.,  0.,  0.,  1.]])

In [3]:
Aug = row_add(Aug, 0, 1, -0.5)
Aug = row_add(Aug, 0, 2, -1)
Aug = row_scale(Aug, 0, 0.5)
Aug

array([[ 1. , -1. ,  0. ,  0.5,  0. ,  0. ],
       [ 0. ,  5. ,  1. , -0.5,  1. ,  0. ],
       [ 0. ,  6. ,  8. , -1. ,  0. ,  1. ]])

In [4]:
Aug = row_scale(Aug, 1, 1/5.0)
Aug = row_add(Aug, 1, 2, -6)
Aug

array([[ 1. , -1. ,  0. ,  0.5,  0. ,  0. ],
       [ 0. ,  1. ,  0.2, -0.1,  0.2,  0. ],
       [ 0. ,  0. ,  6.8, -0.4, -1.2,  1. ]])

In [5]:
Aug = row_scale(Aug, 2, 1/6.8)
Aug = row_add(Aug, 2, 1, -0.2)
Aug

array([[ 1.        , -1.        ,  0.        ,  0.5       ,  0.        ,
         0.        ],
       [ 0.        ,  1.        ,  0.        , -0.08823529,  0.23529412,
        -0.02941176],
       [ 0.        ,  0.        ,  1.        , -0.05882353, -0.17647059,
         0.14705882]])

In [6]:
A_inv = Aug[:, 3:]
print("Исходная матрица:")
print(A)
print("Обратная матрица:")
print(A_inv)
print("Произведение исходной и обратной матриц:")
print(A_inv @ A)

Исходная матрица:
[[ 2 -2  0]
 [ 1  4  1]
 [ 2  4  8]]
Обратная матрица:
[[ 0.5         0.          0.        ]
 [-0.08823529  0.23529412 -0.02941176]
 [-0.05882353 -0.17647059  0.14705882]]
Произведение исходной и обратной матриц:
[[ 1.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 6.93889390e-18  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]


Видно, что произведение дало почти единичную матрицу, но ошибки округления оставили близкие к нулю, но не нулевые элементы вы -16  и -18 степенях.